<?php

namespace TK\RecitationBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator ;


/**
 * RecitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecitationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($page=1, $maxperpage=20)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('recitateur')
            ->from('TKRecitationBundle:Recitateur','recitateur');

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }
}
