tk_media:
    resource: "@TKMediaBundle/Resources/config/routing.yml"
    prefix:   /

tk_recitation:
    resource: "@TKRecitationBundle/Resources/config/routing.yml"
    prefix:   /

tk_abonnement:
    resource: "@TKAbonnementBundle/Resources/config/routing.yml"
    prefix:   /abonnements

tk_cours:
    resource: "@TKCoursBundle/Resources/config/routing.yml"
    prefix:   /

tk_utilisateur:
    resource: "@TKUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

tk_core:
    resource: "@TKCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:    /login
    defaults: { _controller: TKSecurityBundle:Security:login}

forget:
    path:    /recovery
    defaults: { _controller: TKSecurityBundle:Security:forget}


login_check:
    path:    /login_check

logout:
    path:    /logout
