tk_cours_homepage:
    path:     /cours/liste/{page}
    defaults: { _controller: TKCoursBundle:Cours:all, page: 1 }

tk_cours_add:
    path: /cours/add
    defaults: { _controller: TKCoursBundle:Cours:add }

tk_cours_view:
    path: /cours/view/{id}
    defaults:
        _controller: TKCoursBundle:Cours:view
    requirements:
        id: \d+

tk_cours_edit:
    path: /cours/edit/{id}
    defaults:
        _controller: TKCoursBundle:Cours:edit
    requirements:
        id: \d+

tk_cours_delete:
    path: /cours/delete/{id}
    defaults:
        _controller: TKCoursBundle:Cours:delete
    requirements:
        id: \d+

tk_cours_theme_homepage:
    path: /theme/liste/{page}
    defaults: { _controller: TKCoursBundle:Theme:all, page: 1}

tk_cours_theme_add:
    path: /theme/add
    defaults: { _controller: TKCoursBundle:Theme:add }

tk_cours_theme_edit:
    path: /theme/edit/{id}
    defaults:
        _controller: TKCoursBundle:Theme:edit
    requirements:
        id: \d+

tk_cours_theme_delete:
    path: /theme/delete/{id}
    defaults:
        _controller: TKCoursBundle:Theme:delete
    requirements:
        id: \d+

