<?php

namespace TK\UtilisateurBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator ;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($page=1, $maxperpage=20)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('utilisateur')
            ->from('TKUtilisateurBundle:Utilisateur','utilisateur');

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }
}
