<?php

namespace TK\MediaBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TypeMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMediaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList($page=1, $maxperpage=20)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('type_media')
            ->from('TKMediaBundle:TypeMedia','type_media') ;

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }

}
