tk_utilisateur_homepage:
    path:     /utilisateurs/liste/{page}
    defaults: { _controller: TKUtilisateurBundle:Utilisateur:all, page: 1 }

tk_utilisateur_add:
    path:     /utilisateurs/add
    defaults: { _controller: TKUtilisateurBundle:Utilisateur:add}

tk_utilisateur_view:
    path:    /utilisateurs/view/{id}
    defaults:
        _controller: TKUtilisateurBundle:Utilisateur:view
    requirements:
        id: \d+

tk_utilisateur_delete:
    path:    /utilisateurs/delete/{id}
    defaults:
        _controller: TKUtilisateurBundle:Utilisateur:delete
    requirements:
        id: \d+

tk_etudiant_homepage:
    path:     /etudiants/liste/{page}
    defaults: { _controller: TKUtilisateurBundle:Etudiant:all, page: 1 }

tk_etudiant_add:
    path:     /etudiants/add
    defaults: { _controller: TKUtilisateurBundle:Etudiant:add}

tk_etudiant_view:
    path:    /etudiants/view/{id}
    defaults:
        _controller: TKUtilisateurBundle:Etudiant:view
    requirements:
        id: \d+

tk_etudiant_delete:
    path:    /etudiants/delete/{id}
    defaults:
        _controller: TKUtilisateurBundle:Etudiant:delete
    requirements:
        id: \d+


tk_profile_edit:
    path: /profile
    defaults: { _controller: TKUtilisateurBundle:Profil:edit }
